name: grapht
dependencies:
  - certifi=2024.2.2
  - charset-normalizer=3.3.2
  - contourpy=1.1.1
  - cycler=0.12.1
  - filelock=3.13.1
  - fonttools=4.49.0
  - fsspec=2024.2.0
  - huggingface_hub=0.21.0
  - idna=3.6
  - importlib_resources=6.1.2
  - joblib=1.3.2
  - kiwisolver=1.4.5
  - matplotlib=3.7.5
  - numpy=1.24.4
  - packaging=23.2
  - pillow=10.2.0
  - pip=24.0
  - pyparsing=3.1.1
  - python-dateutil=2.8.2
  - pyyaml=6.0.1
  - regex=2023.12.25
  - requests=2.31.0
  - safetensors=0.4.2
  - scikit-learn=1.3.2
  - scipy=1.10.1
  - setuptools=68.2.2
  - six=1.16.0
  - threadpoolctl=3.3.0
  - tokenizers=0.15.2
  - torch=1.12.0+cu113
  - tqdm=4.66.2
  - transformers=4.38.1
  - typing_extensions=4.10.0
  - urllib3=2.2.1
  - wheel=0.41.2
  - zipp=3.17.0

